version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: unless-stopped
    env_file:
      - ./creds.env

    ports: 
      - 8080:8080

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=technik@eizi.at
      - STAGING=0 #1=Use Lets Encrypt Test CA / 0 Use Lets Encrypt Productive CA (with rate-limits)
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/user_conf.d/ # More information: https://hub.docker.com/_/nginx
      - SERVER_NAME=keyserver.eizi.at
    
    ports:
      - 443:443
      - 80:80
      
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - type: bind
        source: ./nginx/nginx.conf.template
        target: /etc/nginx/templates/nginx.conf.template

volumes:
  nginx_secrets: